### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by meduza** [VeliovGroup/Meteor-Leaderboard-Neo4j#11]
App Exited with code: 8:

``` javascript
$ meteor
[[[[[ ~/Sites/Meteor-Leaderboard-Neo4j ]]]]]  

=> Started proxy.                             
=> Started MongoDB.                           
W20150124-11:41:05.945(3)? (STDERR)           
W20150124-11:41:05.946(3)? (STDERR) /Users/medvedev/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150124-11:41:05.946(3)? (STDERR)                         throw(ex);
W20150124-11:41:05.947(3)? (STDERR)                               ^
W20150124-11:41:05.947(3)? (STDERR) TypeError: undefined is not a function
W20150124-11:41:05.947(3)? (STDERR)     at Object.neo4j.init (packages/ostrio:neo4jreactivity/ostrio:neo4jreactivity_driver.js:385:1)
W20150124-11:41:05.947(3)? (STDERR)     at Meteor.neo4j (packages/ostrio:neo4jreactivity/ostrio:neo4jreactivity_driver.js:611:1)
W20150124-11:41:05.947(3)? (STDERR)     at /Users/medvedev/Sites/Meteor-Leaderboard-Neo4j/.meteor/local/build/programs/server/packages/ostrio_neo4jreactivity.js:634:4
W20150124-11:41:05.947(3)? (STDERR)     at /Users/medvedev/Sites/Meteor-Leaderboard-Neo4j/.meteor/local/build/programs/server/packages/ostrio_neo4jreactivity.js:749:3
W20150124-11:41:05.947(3)? (STDERR)     at /Users/medvedev/Sites/Meteor-Leaderboard-Neo4j/.meteor/local/build/programs/server/boot.js:205:10
W20150124-11:41:05.948(3)? (STDERR)     at Array.forEach (native)
W20150124-11:41:05.948(3)? (STDERR)     at Function._.each._.forEach (/Users/medvedev/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150124-11:41:05.949(3)? (STDERR)     at /Users/medvedev/Sites/Meteor-Leaderboard-Neo4j/.meteor/local/build/programs/server/boot.js:116:5
=> Exited with code: 8

```

Packages:

meteor@1.1.4
meteor-platform@1.2.1
meteorhacks:async@1.0.0
meteorhacks:npm@1.2.2
ostrio:neo4jdriver@0.2.5
ostrio:neo4jreactivity@0.4.6

**Comment by dr-dimitru** [comment]
Hi @meduza ,
This issue will be fixed in next release - very soon

**Comment by dr-dimitru** [comment]
@meduza fixed in: https://github.com/VeliovGroup/ostrio-Neo4jreactivity/commit/3ca874c490bd51c6f39010727a8190a50e09969e

**Comment by meduza** [comment]
@dr-dimitru now it works! 👍
