### ISSUE TITLE
ReactiveVar is not defined + No data?

### ISSUE THREAD

**Issue by lifeinchords** [VeliovGroup/Meteor-Leaderboard-Neo4j#7]
After loading up the app, in my console, I get
`Uncaught ReferenceError: ReactiveVar is not defined`

![screen shot 2015-01-16 at 9 57 40 am](https://cloud.githubusercontent.com/assets/716168/5778045/2449dae6-9d66-11e4-94b9-fda7e5832f4f.png)

It seems the app is loading without data.

My neo4J dB is running..

```
/usr/local/bin/neo4j start
Using additional JVM arguments:  -server -XX:+DisableExplicitGC -Dorg.neo4j.server.properties=conf/neo4j-server.properties -Djava.util.logging.config.file=conf/logging.properties -Dlog4j.configuration=file:conf/log4j.properties -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Dneo4j.ext.udc.source=homebrew -Djava.awt.headless=true
Starting Neo4j Server...WARNING: not changing user
process [6707]... waiting for server to be ready....... OK.
http://localhost:7474/ is ready.
```

**Comment by dr-dimitru** [comment]
Hi @lifeinchords , we already met this issue, try:

``` shell
meteor remove ostrio:neo4jreactivity
meteor add ostrio:neo4jreactivity
```

Let me know does it solves an issue

**Comment by lifeinchords** [comment]
Hmm.. I cloned my directory as you instructed.. I didn't copy it...
but doing that got me past that error.

Now, I have this issue:
Do I need to seed data or something similar?

```
=> Started proxy.
=> Started MongoDB.
I20150116-15:48:22.653(-5)? ** You've set up some data subscriptions with Meteor.publish(), but
I20150116-15:48:22.720(-5)? ** you still have autopublish turned on. Because autopublish is still
I20150116-15:48:22.720(-5)? ** on, your Meteor.publish() calls won't have much effect. All data
I20150116-15:48:22.721(-5)? ** will still be sent to all clients.
I20150116-15:48:22.721(-5)? **
I20150116-15:48:22.721(-5)? ** Turn off autopublish by removing the autopublish package:
I20150116-15:48:22.721(-5)? **
I20150116-15:48:22.721(-5)? **   $ meteor remove autopublish
I20150116-15:48:22.721(-5)? **
I20150116-15:48:22.722(-5)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20150116-15:48:22.722(-5)? ** for each collection that you want clients to see.
I20150116-15:48:22.722(-5)?
W20150116-15:48:22.725(-5)? (STDERR)
W20150116-15:48:22.725(-5)? (STDERR) /Users/xxxxxxxxx/.meteor/packages/meteor-tool/.1.0.38.1t4kxma++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150116-15:48:22.726(-5)? (STDERR)            throw(ex);
W20150116-15:48:22.726(-5)? (STDERR)                  ^
W20150116-15:48:22.726(-5)? (STDERR) TypeError: Cannot read property 'length' of undefined
W20150116-15:48:22.726(-5)? (STDERR)     at neo4j.methods.incrementScore (app/leaderboard.js:59:41)
W20150116-15:48:22.726(-5)? (STDERR)     at /Users/xxxxxxxxx/Code/code/meteor-leaderboard-neo4j/.meteor/local/build/programs/server/boot.js:182:5
=> Exited with code: 8
```

**Comment by dr-dimitru** [comment]
Did you tried run meteor as 'sudo' user?

**Comment by lifeinchords** [comment]
Not sure why sudo would help, but yes, I just tried.. same errors :(

**Comment by dr-dimitru** [comment]
I thought there is some read/write error at internal meteor's files, okay then. 
Do you have any data at neo4j database? 
Could you please check via Neo4j browser, go to localhost:7474

**Comment by lifeinchords** [comment]
I looked at your source and found this query

`Players = neo4j.query('MATCH (a:Player) RETURN a ORDER BY a.score DESC');`

if I run that in the neo4j browser, it appears I'm getting data

![screen shot 2015-01-16 at 11 11 50 pm](https://cloud.githubusercontent.com/assets/716168/5787647/32635f2a-9dd5-11e4-8a2c-ce77e2caff38.png)

Any ideas what is failing?

=: s

**Comment by lifeinchords** [comment]
So i deleted the directory, and re-cloned, this time it worked.

neo4j is running before I started any of this, so maybe that's why? not sure... here's my output

```
[18:32][user@compname:~/Code/code]$ git clone git@github.com:VeliovGroup/Meteor-Leaderboard-Neo4j.git
Cloning into 'Meteor-Leaderboard-Neo4j'...
remote: Counting objects: 56, done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 56 (delta 13), reused 49 (delta 9)
Receiving objects: 100% (56/56), 12.26 KiB | 0 bytes/s, done.
Resolving deltas: 100% (13/13), done.
Checking connectivity... done.

[19:22][user@compname:~/Code/code]$ cd Meteor-Leaderboard-Neo4j/

[19:22][user@compname:~/Code/code/Meteor-Leaderboard-Neo4j(master)]$ ls
leaderboard.css   leaderboard.js    packages    readme.md
leaderboard.html  lib     packages.json

[19:23][user@compname:~/Code/code/Meteor-Leaderboard-Neo4j(master)]$ meteor list
npm-container: updating npm dependencies -- neo4j...
autopublish             1.0.2  Publish the entire database to all clients
insecure                1.0.2  Allow all database writes by default
meteor-platform         1.2.1  Include a standard set of Meteor packages in your app
npm-container           1.0.0+ Contains all your npm dependencies
ostrio:neo4jreactivity  0.4.2  Meteor.js Neo4j database pseudo-reactivity layer


+ These packages are built locally from source.

[19:23][user@compname:~/Code/code/Meteor-Leaderboard-Neo4j(master)]$ meteor remove ostrio:neo4jreactivity

Changes to your project's package version selections:

meteorhacks:async       removed from your project
meteorhacks:npm         removed from your project
ostrio:neo4jdriver      removed from your project
ostrio:neo4jreactivity  removed from your project
sha                     removed from your project

ostrio:neo4jreactivity: removed dependency

[19:23][user@compname:~/Code/code/Meteor-Leaderboard-Neo4j(master)]$ meteor add ostrio:neo4jreactivity

Changes to your project's package version selections:

meteorhacks:async       added, version 1.0.0
meteorhacks:npm         added, version 1.2.2
ostrio:neo4jdriver      added, version 0.2.5
ostrio:neo4jreactivity  added, version 0.4.2
sha                     added, version 1.0.2


ostrio:neo4jreactivity: Meteor.js Neo4j database pseudo-reactivity layer

[19:23][user@compname:~/Code/code/Meteor-Leaderboard-Neo4j(master)]$ npm -g install neo4j
neo4j@1.1.1 /usr/local/lib/node_modules/neo4j
├── http-status@0.1.8
└── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, tough-cookie@0.12.1, http-signature@0.10.1, bl@0.9.3, form-data@0.2.0, hawk@1.1.1)

[19:24][user@compname:~/Code/code/Meteor-Leaderboard-Neo4j(master)]$ meteor
[[[[[ ~/Code/code/Meteor-Leaderboard-Neo4j ]]]]]

=> Started proxy.
=> Started MongoDB.
I20150117-19:24:19.836(-5)? ** You've set up some data subscriptions with Meteor.publish(), but
I20150117-19:24:20.074(-5)? ** you still have autopublish turned on. Because autopublish is still
I20150117-19:24:20.074(-5)? ** on, your Meteor.publish() calls won't have much effect. All data
I20150117-19:24:20.074(-5)? ** will still be sent to all clients.
I20150117-19:24:20.074(-5)? **
I20150117-19:24:20.075(-5)? ** Turn off autopublish by removing the autopublish package:
I20150117-19:24:20.075(-5)? **
I20150117-19:24:20.075(-5)? **   $ meteor remove autopublish
I20150117-19:24:20.075(-5)? **
I20150117-19:24:20.075(-5)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20150117-19:24:20.076(-5)? ** for each collection that you want clients to see.
I20150117-19:24:20.076(-5)?
=> Started your app.

=> App running at: http://localhost:3000/
```

**Comment by dr-dimitru** [comment]
@lifeinchords yes, neo4j DB must be running before you start Meteor.
Glad you've solved an issue
